### ISSUE TITLE
Adding krakentools to IUC

### ISSUE THREAD

**Issue by paulzierep** [jvolkening/galaxy-tools#3]
We are currently completing the set of krakentools for galaxy (https://github.com/galaxyproject/tools-iuc/tree/3dfd5d7d5870695d24d2ede7b321bcaac25e0209/tools/krakentools) and I saw that you already made a wrapper for extract_kraken_reads 
Do you mind if we include that wrapper into the suite and maintain it from there ?

**Comment by jvolkening** [comment]
Absolutely, please do. Just let me know when you do and I will deprecate it here.

**Comment by paulzierep** [comment]
Perfect, thanks. I will send you the PR in the IUC when it's done. You will be credited of course.

**Comment by paulzierep** [comment]
Would you like to review https://github.com/galaxyproject/tools-iuc/pull/5143 ?

**Comment by jvolkening** [comment]
Looks fine to me (I agree with Matthias about the indentation, but that's opinion).

**Comment by paulzierep** [comment]
I think you can close this and deprecate the tool, it is merged, best Paul
